CREATE TABLE IF NOT EXISTS public.player
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    balance numeric(10,2) NOT NULL,
    email character varying(255) COLLATE pg_catalog."default" NOT NULL,
    password character varying(255) COLLATE pg_catalog."default" NOT NULL,
    username character varying(255) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT player_pkey PRIMARY KEY (id),
    CONSTRAINT uko39xn8lmj05iew7d2tgw836jy UNIQUE (username),
    CONSTRAINT ukoivbimcon0iqmb8efpv723h08 UNIQUE (email)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.player
    OWNER to postgres;

CREATE TABLE IF NOT EXISTS public.ticket
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    placed_at timestamp(6) without time zone NOT NULL,
    potential_payout numeric(10,2) NOT NULL,
    stake numeric(10,2) NOT NULL,
    status character varying(255) COLLATE pg_catalog."default" NOT NULL,
    total_odds numeric(10,2) NOT NULL,
    player_id bigint,
    CONSTRAINT ticket_pkey PRIMARY KEY (id),
    CONSTRAINT fkp9q4f1vh96mjeej5iyq180q7w FOREIGN KEY (player_id)
        REFERENCES public.player (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT ticket_status_check CHECK (status::text = ANY (ARRAY['PENDING'::character varying, 'WON'::character varying, 'LOST'::character varying]::text[]))
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.ticket
    OWNER to postgres;

CREATE TABLE IF NOT EXISTS public.ticket_selection
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    away_team character varying(255) COLLATE pg_catalog."default",
    event_id bigint,
    event_status character varying(255) COLLATE pg_catalog."default",
    home_team character varying(255) COLLATE pg_catalog."default",
    market_name character varying(255) COLLATE pg_catalog."default",
    odds_at_placement numeric(10,2) NOT NULL,
    outcome_id bigint,
    outcome_name character varying(255) COLLATE pg_catalog."default",
    ticket_id bigint,
    CONSTRAINT ticket_selection_pkey PRIMARY KEY (id),
    CONSTRAINT fkj3g2elehokm6bqh0g89j66yks FOREIGN KEY (ticket_id)
        REFERENCES public.ticket (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.ticket_selection
    OWNER to postgres;