CREATE TABLE IF NOT EXISTS public.odds_tenant
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    outcome_id bigint NOT NULL UNIQUE,
    overridden_odds numeric(10,2) NOT NULL,
    CONSTRAINT odds_tenant_pkey PRIMARY KEY (id)
);