CREATE TABLE IF NOT EXISTS public.sport
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    name character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT sport_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.category
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    name character varying(255) COLLATE pg_catalog."default",
    sport_id bigint,
    CONSTRAINT category_pkey PRIMARY KEY (id),
    CONSTRAINT fk75iwgfu3tye569b7ybmxqvsul FOREIGN KEY (sport_id)
        REFERENCES public.sport (id)
);

CREATE TABLE IF NOT EXISTS public.league
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    name character varying(255) COLLATE pg_catalog."default",
    category_id bigint,
    sport_id bigint,
    CONSTRAINT league_pkey PRIMARY KEY (id),
    CONSTRAINT fk11gkb0t51knp0pqxryy274iaw FOREIGN KEY (sport_id)
        REFERENCES public.sport (id),
    CONSTRAINT fkngtun2nuow3q8a2rvnidmgjkn FOREIGN KEY (category_id)
        REFERENCES public.category (id)
);

CREATE TABLE IF NOT EXISTS public.event
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    away_team character varying(255) COLLATE pg_catalog."default",
    home_team character varying(255) COLLATE pg_catalog."default",
    start_time timestamp(6) without time zone,
    status character varying(255) COLLATE pg_catalog."default",
    league_id bigint,
    CONSTRAINT event_pkey PRIMARY KEY (id),
    CONSTRAINT fk2oontqepc8mddwomq8jdynrrg FOREIGN KEY (league_id)
        REFERENCES public.league (id)
);

CREATE TABLE IF NOT EXISTS public.market_type
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    name character varying(255) COLLATE pg_catalog."default",
    sport_id bigint,
    CONSTRAINT market_type_pkey PRIMARY KEY (id),
    CONSTRAINT fkft9ppycslbl5x21ds8fkawbxc FOREIGN KEY (sport_id)
        REFERENCES public.sport (id)
);

CREATE TABLE IF NOT EXISTS public.outcome_type
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    name character varying(255) COLLATE pg_catalog."default",
    market_type_id bigint,
    CONSTRAINT outcome_type_pkey PRIMARY KEY (id),
    CONSTRAINT fkgvrvqpp5nin4q0e8v5tvq7b5c FOREIGN KEY (market_type_id)
        REFERENCES public.market_type (id)
);

CREATE TABLE IF NOT EXISTS public.market
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    event_id bigint,
    market_type_id bigint,
    CONSTRAINT market_pkey PRIMARY KEY (id),
    CONSTRAINT fkfyteig5j2tdfailovj2fi88lo FOREIGN KEY (market_type_id)
        REFERENCES public.market_type (id),
    CONSTRAINT fkkdwvtgsitfuyvtchmmhgqyldj FOREIGN KEY (event_id)
        REFERENCES public.event (id)
);

CREATE TABLE IF NOT EXISTS public.outcome
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    odds numeric(10,2),
    market_id bigint,
    outcome_type_id bigint,
    CONSTRAINT outcome_pkey PRIMARY KEY (id),
    CONSTRAINT fk8y1r6uec5tpn6iyaugfc1fmsa FOREIGN KEY (market_id)
        REFERENCES public.market (id),
    CONSTRAINT fkpag0eiu5jqb84jmm31xynl4wf FOREIGN KEY (outcome_type_id)
        REFERENCES public.outcome_type (id)
);