CREATE TABLE IF NOT EXISTS public.tenant
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    tenant_key character varying(255) NOT NULL UNIQUE,
    domain character varying(255) NOT NULL UNIQUE,
    brand_name character varying(255),
    primary_color character varying(255),
    logo_url character varying(255),
    CONSTRAINT tenant_pkey PRIMARY KEY (id)
);

INSERT INTO public.tenant (tenant_key, domain, brand_name, primary_color, logo_url)
VALUES
  ('brand_a', 'branda.local', 'Brand A', '#1976d2', ''),
  ('brand_b', 'brandb.local', 'Brand B', '#e53935', '');