CREATE TABLE IF NOT EXISTS public.app_user
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    username character varying(255) NOT NULL UNIQUE,
    password character varying(255) NOT NULL,
    role character varying(50) NOT NULL,
    tenant_key character varying(255),
    CONSTRAINT app_user_pkey PRIMARY KEY (id)
);